require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe WorkordersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Workorder. As you add validations to Workorder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WorkordersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all workorders as @workorders" do
      workorder = Workorder.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:workorders)).to eq([workorder])
    end
  end

  describe "GET #show" do
    it "assigns the requested workorder as @workorder" do
      workorder = Workorder.create! valid_attributes
      get :show, {:id => workorder.to_param}, valid_session
      expect(assigns(:workorder)).to eq(workorder)
    end
  end

  describe "GET #new" do
    it "assigns a new workorder as @workorder" do
      get :new, {}, valid_session
      expect(assigns(:workorder)).to be_a_new(Workorder)
    end
  end

  describe "GET #edit" do
    it "assigns the requested workorder as @workorder" do
      workorder = Workorder.create! valid_attributes
      get :edit, {:id => workorder.to_param}, valid_session
      expect(assigns(:workorder)).to eq(workorder)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Workorder" do
        expect {
          post :create, {:workorder => valid_attributes}, valid_session
        }.to change(Workorder, :count).by(1)
      end

      it "assigns a newly created workorder as @workorder" do
        post :create, {:workorder => valid_attributes}, valid_session
        expect(assigns(:workorder)).to be_a(Workorder)
        expect(assigns(:workorder)).to be_persisted
      end

      it "redirects to the created workorder" do
        post :create, {:workorder => valid_attributes}, valid_session
        expect(response).to redirect_to(Workorder.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved workorder as @workorder" do
        post :create, {:workorder => invalid_attributes}, valid_session
        expect(assigns(:workorder)).to be_a_new(Workorder)
      end

      it "re-renders the 'new' template" do
        post :create, {:workorder => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested workorder" do
        workorder = Workorder.create! valid_attributes
        put :update, {:id => workorder.to_param, :workorder => new_attributes}, valid_session
        workorder.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested workorder as @workorder" do
        workorder = Workorder.create! valid_attributes
        put :update, {:id => workorder.to_param, :workorder => valid_attributes}, valid_session
        expect(assigns(:workorder)).to eq(workorder)
      end

      it "redirects to the workorder" do
        workorder = Workorder.create! valid_attributes
        put :update, {:id => workorder.to_param, :workorder => valid_attributes}, valid_session
        expect(response).to redirect_to(workorder)
      end
    end

    context "with invalid params" do
      it "assigns the workorder as @workorder" do
        workorder = Workorder.create! valid_attributes
        put :update, {:id => workorder.to_param, :workorder => invalid_attributes}, valid_session
        expect(assigns(:workorder)).to eq(workorder)
      end

      it "re-renders the 'edit' template" do
        workorder = Workorder.create! valid_attributes
        put :update, {:id => workorder.to_param, :workorder => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested workorder" do
      workorder = Workorder.create! valid_attributes
      expect {
        delete :destroy, {:id => workorder.to_param}, valid_session
      }.to change(Workorder, :count).by(-1)
    end

    it "redirects to the workorders list" do
      workorder = Workorder.create! valid_attributes
      delete :destroy, {:id => workorder.to_param}, valid_session
      expect(response).to redirect_to(workorders_url)
    end
  end

end
